# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Model\UserInterface: bcrypt
        AppBundle\Model\ProtectableInterface: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        consigna_user_provider:
            id: 'consigna.user.provider'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            lexik_jwt: ~

        main:
            pattern: '^/'
            guard:
                provider: 'consigna_user_provider'
                authenticators:
                    - 'consigna.admin.authenticator'
            form_login:
                always_use_default_target_path: false
                target_path_parameter:          '_target_path'
            logout:
                path: '/logout'
                target: '/'
            anonymous:   true
            switch_user: true

    access_control:
        - { path: '^/api/login', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/api/doc',   roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/api',       roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/login$',    roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/logout$',   roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: '^/connect',   roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: '^/check',     roles: 'IS_AUTHENTICATED_FULLY' }
        - { path: '^/',          roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }